### ISSUE TITLE
Atualização Documentação

### ISSUE THREAD

**Issue by eduardomioto** [ESEGroup/IssuesAuthenticatorCascavel#32]
Olá Srs. bom dia. Sou um dos revisores dos documentos produzidos por vocês, me chamo Eduardo Mioto, mestrando do PESC, e naturalmente aluno do Prof. Guilherme na disciplina de VV&T. Nosso outro revisor é o mestrando Irving Oliveira, que possui grande experiência em desenvolvimento e teste de software, e vem sendo peça fundamental para a revisão dos documentos.  

**Gostaria de lhes solicitar que atualizem a documentação com os novos documentos corrigidos para que possamos seguir com a análise e criação do plano de testes baseado na documentação atualizada. Sem esta, o planejamento dos testes ficará impactado.**

Em caso de dúvidas sobre os pontos de não-conformidade que citamos nos documentos, fiquem a vontade para o contato via email enviando para **irvingoliveira@cos.ufrj.br** e **mioto@cos.ufrj.br**

Obrigado.
Tenham uma ótima semana.
Eduardo Mioto

**Comment by pedrorv** [comment]
Boa tarde, hoje a noite iremos atualizar os documentos.

**Comment by eduardomioto** [comment]
OK Pedro. Obrigado.

**Comment by pedrorv** [comment]
Boa tarde, Eduardo. Os documentos foram atualizados. Desculpe a demora.
