### ISSUE TITLE
Serviços inacessíveis

### ISSUE THREAD

**Issue by irvingoliveira** [ESEGroup/IssuesAuthenticatorCascavel#54]
Os serviços registrar_saida_authenticator, registrar_entrada_authenticator e atualizar_preferencias_authenticator, quando requisitados, exibem a seguinte mensagem de erro: "sqlite3.OperationalError: database is locked", impossibilitando assim os testes.

**Comment by pedrorv** [comment]
Não sei bem o que aconteceu mas reiniciei o servidor e voltou a funcionar normalmente.

**Comment by irvingoliveira** [comment]
Realizei um teste e, ao tentar realizar novamente, o problema tornou a ocorrer.

**Comment by pedrorv** [comment]
Qual foi o teste?

**Comment by irvingoliveira** [comment]
Os testes são funcionais e visam somente o envio de dados para os seus serviços e ver como eles se comportam. A questão é que tem algo ocorrendo durante as operações que está fazendo com o que banco de dados trave. A mensagem que estou recebendo em todos os serviços, exceto o de validar usuário é esta:

sqlite3.OperationalError: database is locked.

A falha ocorre mesmo com o envio de dados válidos.

**Comment by pedrorv** [comment]
Qual ferramenta está sendo utilizada para os testes? Desliguei e liguei o servidor novamente e fiz os testes dos serviços utilizando Postman e funcionou normalmente.

**Comment by irvingoliveira** [comment]
Está sendo utilizado o SoapUI. Parece que o problema ocorre quando acontece um erro de integridade. No teste, preciso aferir como o sistema trata o envio de dados nulos por exemplo. Porém, quando envio, após o sistema exibir mensagem de erro sobre integridade (não tratada) ele entra neste estado de lock. Por sinal está bloqueado novamente. Irei fechar esta issue e abrir outra específica para este problema.
