### ISSUE TITLE
Erros de integridade não tratados

### ISSUE THREAD

**Issue by irvingoliveira** [ESEGroup/IssuesAuthenticatorCascavel#56]
Ao enviar dados nulos onde não são permitidos nos serviços de registrar entrada, saída e de atualizar preferências, o sistema não exibe uma mensagem tratada, acarretando em erro 500.

**Comment by pedrorv** [comment]
Pode realizar o teste novamente?

**Comment by irvingoliveira** [comment]
Agora as mensagens estão sendo exibidas com o devido tratamento.
